layout_spectrum: 0.6953405
color:
  saturation: 0.6362007
  brandStrength: 0.5086069
  lightness: 1
  rhythmicContrast: 0.1756272
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0
name: shawnharris.info
